[project]
name = "Fe_XIII_dens"
version = "0.0.1"
dependencies = ["numpy","scipy","datetime","tqdm"]
description = "Density computation utilities"
authors = [{name = "Alin Paraschiv"}]
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.10"

[tool.setuptools]
py-modules=["Fe_XIII_dens"]
